title: Nahum Meherete # your name (or website title) here
logo: "/images/Nahum_Grad-013.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data analyst looking for roles and opportunities in Data Science, Machine Learning, Data Visualization, and Data Analytics. Well versed in Python, R, and C++. Proficient in using Sci-kitLearn, Matplotlib, Keras, Tensorflow, Pandas, and Pytorch.
  <br><br>
  
  <a href="https://www.linkedin.com/in/nahum-meherete/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-165640139-1 # your Google Analytics tracking ID here
